### ISSUE TITLE
No addons found

### ISSUE THREAD

**Issue by narcisgarcia** [i96751414/repository.github#1]
Tried with Kodi 19.3.0 and I don't find any Github extension but i96751414 ones (torrest, flix, etc).

**Comment by i96751414** [comment]
What do you mean? By default this repository only finds i96 addons. To find others you need to add the repository entry.

**Comment by narcisgarcia** [comment]
> To find others you need to add the repository entry.

Some step-by-step guide to do this?

Does this extension have some helper feature to not have to type in each `h t t p : / / . . .` character?

**Comment by i96751414** [comment]
See addon entries section: https://github.com/i96751414/repository.github#add-on-entries
