### ISSUE TITLE
Support showing several last versions of a single addon

### ISSUE THREAD

**Issue by antonsoroko** [i96751414/repository.github#3]
Would be nice to support showing multiple versions of an addon, so user can easily downgrade addon if needed.
E.g. read list of github releases and take last 5 versions and construct addon.xml with these 5 versions of addon.
So when user will open repo and click on addon and click on versions - user will see 5 versions of addon. The same way it is done for "classic" (static) repos.

Or it can be option if it will affect performance, since i have seen "rate limit" errors from github in log file.

**Comment by i96751414** [comment]
This could certainly be done, however it would defeat the purpose of the repository, right? By specifying a fixed version for an addon, you wouldn't be able to receive updates

By the way, this is already somehow supported if you specify an addon entry with a fixed branch/release version.

**Comment by antonsoroko** [comment]
Hi.

>By specifying a fixed version

i think you completely misunderstood me.

i am not talking about specifying a fixed version. i am talking about dynamically reading github releases page and  dynamically creating addon.xml (like it is now) but for several last versions (right now it is 1 last version).

So user will always see, for example, 5  latest versions (not some manually specified 5 fixed versions, but 5 latest versions from github).
By "see" i mean: when user will open repo and click on addon and click on versions - user will see 5 versions of addon. The same way it is done for "classic" (static) repos.

Hopefully it is more clear now.

**Comment by antonsoroko** [comment]
Looks like i was confused about what kodi repos can do.
After reading some docs i can see that:
One repo can have only one version of the plugin, with one exception: you can have multiple version of addon, each for specific kodi version. so anyway, for one kodi version repo can have only one version of addon.

only if there are multiple repos with same addon (but with different versions of that addon) - then you can see all versions of that addon in addon's info page.
![image](https://github.com/i96751414/repository.github/assets/17964763/60b0ade7-31ba-4045-9c05-f162c19c2ab1)


and i was confused by this. i thought that repo can have multiple version of package, like linux repos, for example. but no.

this sucks very much :-D 

sorry for confusion.

**Comment by i96751414** [comment]
No worries 😛
